[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_insurance_protocol = "AqwQujYBLfiTtK6mc76fLTUTQq5RpXVpwNAPzKdMEXJy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dinesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
